---
output:
  html_document: default
  pdf_document: default
---
Load Library 
```{r}
install.packages("ggplot2", dependencies = TRUE)
library(factoextra)
library(ggplot2)
library(gplots)
```


```{r}
PorpigliaSET <- read.csv('../../Data/Porpiglia/FR-FCM-ZY3K_gated.csv')

#d0 PCA
d0PorpigliaSet <- PorpigliaSET[PorpigliaSET$sample == "Day0",]

d0Por.PCA <- prcomp(d0PorpigliaSet[,(4:25)], center = TRUE,scale. = TRUE)

#d3 PCA
d3PorpigliaSet <- PorpigliaSET[PorpigliaSET$sample == "Day3",]

d3Por.PCA <- prcomp(d3PorpigliaSet[,(4:25)], center = TRUE,scale. = TRUE)

#d6 PCA
d6PorpigliaSet <- PorpigliaSET[PorpigliaSET$sample == "Day6",]

d6Por.PCA <- prcomp(d6PorpigliaSet[,(4:25)], center = TRUE,scale. = TRUE)
```


Explained Variances 
```{r Explained Variances, echo=FALSE}
par(mar=c(0,0,0,0), oma=c(3,3,3,3), mfrow=c(4, 3))

plot(fviz_eig(d0Por.PCA, title = "d0"))
plot(fviz_eig(d3Por.PCA, title = "d3"))
plot(fviz_eig(d6Por.PCA, title = "d6"))
```

Variables PCA: Related factors trend in the same direction 
```{r Variable PCA, echo=FALSE}
plot(fviz_pca_var(d0Por.PCA, title = "d0", repel = TRUE))
plot(fviz_pca_var(d3Por.PCA, title = "d3", repel = TRUE))
plot(fviz_pca_var(d6Por.PCA, title = "d6", repel = TRUE))
```


```{r Individuals PCA, echo=FALSE}
plot(fviz_pca_ind(d0Por.PCA, title = "d0"))
plot(fviz_pca_ind(d3Por.PCA, title = "d3"))
plot(fviz_pca_ind(d6Por.PCA, title = "d6"))
```


```{r BiPlot PCA, echo=FALSE}
plot(fviz_pca_biplot(d0Por.PCA, title = "d0"))
plot(fviz_pca_biplot(d3Por.PCA, title = "d3"))
plot(fviz_pca_biplot(d6Por.PCA, title = "d6"))


```


```{r}
par(mar=c(0,0,2,0), oma=c(4,4,4,4), mfrow=c(1, 3))

plot(d0Por.PCA$x[,1:2], main = "d0", frame.plot = "TRUE", ylab = "Dim1", xlab = "Dim2")
plot(d3Por.PCA$x[,1:2], frame.plot = "TRUE", main = "d3", xlab = "Dim2")
plot(d6Por.PCA$x[,1:2], frame.plot = "TRUE", main = "d6", xlab = "Dim2")

mtext("DIM_1", side=2, line=3, adj=0.5, cex=1, col="Black", outer=TRUE)

mtext("DIM_2", side=1, line=3, adj=0.15, cex=1, col="Black", outer=TRUE)
mtext("DIM_2", side=1, line=3, adj=0.5, cex=1, col="Black", outer=TRUE)
mtext("DIM_2", side=1, line=3, adj=0.85, cex=1, col="Black", outer=TRUE)
```

Fig1: Principal component analysis (PCA) of Myogenic Lineage following wounding. Panels revel transiently altered PCA elements of muscle lineage wouding.  


